name: vistoria_imoveis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core & UI ---
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1

  # --- Firebase (Backend) ---
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4

  # --- State Management & DI (Riverpod) ---
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # --- Navigation ---
  go_router: ^13.1.0

  # MÃ­dia e Filesystem
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  cached_network_image: ^3.3.0

  # Conectividade e Testes
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  # --- Utils ---
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  uuid: ^4.3.3
  intl: ^0.20.2
  firebase_storage: ^11.6.0
  pdf: ^3.11.3
  printing: ^5.14.2
  http: ^1.6.0
  flex_color_scheme: ^8.4.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3

dev_dependencies:
    # --- Testing ---   
  flutter_test:
    sdk: flutter
  integration_test :
    sdk: flutter

  # --- Code Generation ---
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  
  # --- Linting ---
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.7
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true