name: vistoria_imoveis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core & UI ---
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # --- Firebase (Backend) ---
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # --- State Management & DI (Riverpod) ---
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # --- Navigation ---
  go_router: ^13.1.0

  # --- Utils ---
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  uuid: ^4.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Code Generation ---
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  
  # --- Linting ---
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true